# params.yaml
datasets:
  BF-C2DL-HSC:
    default_crop_size: 64
    crop_sizes: [64]
  BF-C2DL-MuSC:
    default_crop_size: 256
    crop_sizes: [64, 128, 192, 256, 320, 512]
  DIC-C2DH-HeLa:
    default_crop_size: 256
    crop_sizes: [256]
  Fluo-C2DL-MSC:
    default_crop_size: 1024
    crop_sizes: [1024]

  Fluo-N2DH-GOWT1:
    default_crop_size: 160
    crop_sizes: [160]
